name: Deploy fastapi Backend to Cloud Run

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend/**"
      - ".github/workflows/backend-deploy.yml"

jobs:
  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest

    steps:
      # ---------------------------------------------------
      # 1. Checkout Repository
      # ---------------------------------------------------
      - name: Checkout code
        uses: actions/checkout@v4

      # ---------------------------------------------------
      # 2. Authenticate to Google Cloud
      # ---------------------------------------------------
      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # ---------------------------------------------------
      # 3. Setup gcloud CLI
      # ---------------------------------------------------
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # ---------------------------------------------------
      # 4. Configure Docker to use gcloud as credential helper
      # ---------------------------------------------------
      - name: Configure Docker Auth
        run: |
          gcloud auth configure-docker asia-east1-docker.pkg.dev


      # ---------------------------------------------------
      # 5. Build Docker Image for backend
      # ---------------------------------------------------
      - name: Build Docker Image (FastAPI Backend)
        run: |
          IMAGE="asia-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/backend/fastapi-backend"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          docker build -t "$IMAGE:latest" ./backend

      # ---------------------------------------------------
      # 6. Push Image to Artifact Registry
      # ---------------------------------------------------
      - name: Push to Artifact Registry
        run: |
          echo "$GITHUB_ENV"
          docker push "$IMAGE:latest"

      # ---------------------------------------------------
      # 7. Deploy to Cloud Run
      # ---------------------------------------------------
      - name: Deploy to Cloud Run
        run: >
          gcloud run deploy fastapi-backend
          --image="$IMAGE:latest"
          --platform=managed
          --region=${{ secrets.CLOUD_RUN_REGION }}
          --allow-unauthenticated
          --port=8080